# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DW's Blog
email: retimes@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog for DW. An astrophysicst, a student, and etc. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dwhan89@github.io" # the base hostname & protocol for your site
twitter_username: dwhan89
github_username:  dwhan89

# Build settings
markdown: kramdown
